---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module
  labels:
    app.kubernetes.io/name: module
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: module
  template:
    metadata:
      labels:
        app.kubernetes.io/name: module
    spec:
      containers:
        - name: module
          image: module
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
