---
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: module
      context: ./..
      docker:
        dockerfile: demo/module/Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
